FROM python:3

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install Playwright's Chromium browser and its OS dependencies
RUN playwright install --with-deps chromium

COPY opentable_bot/* /app/

ENTRYPOINT ["python", "opentable_bot.py"]
